Grade: 
prefix:
effets:
PermsDefault:
  news:
    deleteMemberComm: 
    editMemberComm: 
  support:
    closeTicket: 
    deleteMemberComm: 
    editMemberComm: 
    displayTicket:
  chat:
    color:
  forum:
    perms:
PermsPanel:
  access: 
  info:
    showPage: 
    details:
      showModal: 
      player: 
      console: 
      command: 
      plugins: 
      server: 
    stats:
      visitors:
        showTable: 
      members:
        showTable: 
        editLimitIp: 
        editEmail: 
      activity:
        showTable: 
      shop:
        showTable: 
  general:
    showPage: 
    actions:
      editGeneral: 
  theme:
    showPage: 
    actions:
      editTheme: 
      editBackground: 
      editTypeBackground: 
  home:
    showPage: 
    actions:
      uploadSlider: 
      editSlider: 
      uploadMiniature: 
      editMiniature: 
      addSlider: 
  server:
    showPage: 
    actions:
      addServer: 
      editServer: 
  pages:
    showPage: 
    actions:
      editPage: 
      addPage: 
  news:
    showPage: 
    actions:
      addNews: 
      editNews: 
  shop:
    showPage: 
    actions:
      addCategorie: 
      addOffre: 
      editCategorieOffre: 
      createCoupon:
      modifCoupon:
  payment:
    showPage: 
    actions:
      editPayment: 
      addOffrePaypal: 
      editOffrePaypal: 
  menus:
    showPage: 
    actions:
      addLinkMenu: 
      addDropLinkMenu: 
      editDropAndLinkMenu: 
  vote:
    showPage: 
    actions:
      editSettings: 
      addVote: 
      resetVote: 
      deleteVote: 
  members:
    showPage: 
    actions:
      editMember: 
  forum:
    showPage:
    actions:
      addSmiley:
      seeSmileys:
      addPrefix:
      seePrefix:
  widgets:
    showPage: 
    actions:
      addWidgets: 
      editWidgets: 
  support:
    showPage: 
    tickets:
      showPage: 
      actions:
        editEtatTicket: 
        deleteTicket: 
    maintenance:
      showPage: 
      actions:
        editDefaultMessage: 
        editAdminMessage: 
        editEtatMaintenance: 
        switchRedirectMode: 
  update:
    showPage: 
PermsForum: 
  general: 
      addCategorie: 
      addForum: 
      deleteForum: 
      deleteCategorie: 
      addSousForum: 
      deleteSousForum: 
      modeJoueur:
  moderation: 
      editTopic: 
      deleteMessage: 
      deleteTopic: 
      editMessage: 
      closeTopic: 
      mooveTopic: 
      seeSignalement: 
      addPrefix:
      epingle: 
      selTopic: