#Ce fichier contiens la config de base du serveur---
Pied:
    facebook: '#'
    twitter: https://twitter.com/craftmywebsite
    youtube: https://www.youtube.com/channel/UCzkhnB95d0SCLU2zrTWEBOQ
    discord: https://discord.gg/cVw9UkU